version: '3.8'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile
    container_name: barberopedia-backend
    ports:
        - '5050:5050'
    environment:
        - APP_ENV=development
    depends_on:
        - mongodb
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    container_name: barberopedia-frontend
    ports:
        - '3000:3000'
    environment:
        - APP_ENV=development
    depends_on:
        - mongodb
volumes:
  mongodb-data: